//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using Newtonsoft.Json;

namespace PayPal.Api
{
    /// <summary>
    /// Base Address object used as billing address in a payment or extended for Shipping Address.
    /// <para>
    /// See <a href="https://developer.paypal.com/docs/api/">PayPal Developer documentation</a> for more information.
    /// </para>
    /// </summary>
    public class Address : BaseAddress
    {
        /// <summary>
        /// Phone number in E.123 format. 50 characters max.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "phone")]
        public string phone { get; set; }

        /// <summary>
        /// Address normalization status, returned only for payers from Brazil.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "normalization_status")]
        public new string normalization_status { get; set; }

        /// <summary>
        /// Address status
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "status")]
        public new string status { get; set; }

        /// <summary>
        /// Type of address (e.g., HOME_OR_WORK, GIFT etc).
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "type")]
        public string type { get; set; }
    }
}
