//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using Newtonsoft.Json;

namespace PayPal.Api
{
    /// <summary>
    /// Additional details of the payment amount.
    /// <para>
    /// See <a href="https://developer.paypal.com/docs/api/">PayPal Developer documentation</a> for more information.
    /// </para>
    /// </summary>
    public class Details : PayPalSerializableObject
    {
        /// <summary>
        /// Amount of the subtotal of the items. **Required** if line items are specified. 10 characters max, with support for 2 decimal places.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "subtotal")]
        public string subtotal { get; set; }

        /// <summary>
        /// Amount charged for shipping. 10 characters max with support for 2 decimal places.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "shipping")]
        public string shipping { get; set; }

        /// <summary>
        /// Amount charged for tax. 10 characters max with support for 2 decimal places.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "tax")]
        public string tax { get; set; }

        /// <summary>
        /// Amount being charged for the handling fee. Only supported when the `payment_method` is set to `paypal`.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "handling_fee")]
        public string handling_fee { get; set; }

        /// <summary>
        /// Amount being discounted for the shipping fee. Only supported when the `payment_method` is set to `paypal`.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "shipping_discount")]
        public string shipping_discount { get; set; }

        /// <summary>
        /// Amount being charged for the insurance fee. Only supported when the `payment_method` is set to `paypal`.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "insurance")]
        public string insurance { get; set; }

        /// <summary>
        /// Amount being charged as gift wrap fee.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "gift_wrap")]
        public string gift_wrap { get; set; }

        /// <summary>
        /// Fee charged by PayPal. In case of a refund, this is the fee amount refunded to the original receipient of the payment.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "fee")]
        public string fee { get; set; }
    }
}
