//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using Newtonsoft.Json;

namespace PayPal.Api
{
    /// <summary>
    /// Parameters for flow configuration.
    /// <para>
    /// See <a href="https://developer.paypal.com/docs/api/">PayPal Developer documentation</a> for more information.
    /// </para>
    /// </summary>
    public class FlowConfig : PayPalSerializableObject
    {
        /// <summary>
        /// The type of landing page to display on the PayPal site for user checkout. Set to `Billing` to use the non-PayPal account landing page. Set to `Login` to use the PayPal account login landing page.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "landing_page_type")]
        public string landing_page_type { get; set; }

        /// <summary>
        /// The merchant site URL to display after a bank transfer payment. Valid for only the Giropay or bank transfer payment method in Germany.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "bank_txn_pending_url")]
        public string bank_txn_pending_url { get; set; }

        /// <summary>
        /// Defines whether buyers can complete purchases on the PayPal or merchant website.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "user_action")]
        public string user_action { get; set; }

        /// <summary>
        /// The HTTP method to use to redirect the user to a return URL. Valid value is `GET` or `POST`.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "return_uri_http_method")]
        public string return_uri_http_method { get; set; }
    }
}
