//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using Newtonsoft.Json;

namespace PayPal.Api
{
    /// <summary>
    /// Additional detail of the funding.
    /// <para>
    /// See <a href="https://developer.paypal.com/docs/api/">PayPal Developer documentation</a> for more information.
    /// </para>
    /// </summary>
    public class FundingDetail : PayPalSerializableObject
    {
        /// <summary>
        /// Expected clearing time
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "clearing_time")]
        public string clearing_time { get; set; }

        /// <summary>
        /// [DEPRECATED] Hold-off duration of the payment. payment_debit_date should be used instead.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "payment_hold_date")]
        public string payment_hold_date { get; set; }

        /// <summary>
        /// Date when funds will be debited from the payer's account
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "payment_debit_date")]
        public string payment_debit_date { get; set; }

        /// <summary>
        /// Processing type of the payment card
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "processing_type")]
        public string processing_type { get; set; }
    }
}
