//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using System.Collections.Generic;
using Newtonsoft.Json;

namespace PayPal.Api
{
    /// <summary>
    /// List of merchant templates.
    /// <para>
    /// See <a href="https://developer.paypal.com/docs/api/">PayPal Developer documentation</a> for more information.
    /// </para>
    /// </summary>
    public class InvoiceTemplates : PayPalResource
    {
        /// <summary>
        /// List of addresses in merchant profile.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "addresses")]
        public List<Address> addresses { get; set; }

        /// <summary>
        /// List of emails in merchant profile.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "emails")]
        public List<string> emails { get; set; }

        /// <summary>
        /// List of phone numbers in merchant profile.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "phones")]
        public List<Phone> phones { get; set; }

        /// <summary>
        /// An array of templates.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "templates")]
        public List<InvoiceTemplate> templates { get; set; }
    }
}
