//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using System.Collections.Generic;
using Newtonsoft.Json;

namespace PayPal.Api
{
    /// <summary>
    /// Details of a list of purchasable items and shipping information included with a payment transaction.
    /// </summary>
    public class ItemList : PayPalSerializableObject
    {
        /// <summary>
        /// List of items.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "items")]
        public List<Item> items { get; set; }

        /// <summary>
        /// Shipping address.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "shipping_address")]
        public ShippingAddress shipping_address { get; set; }

        /// <summary>
        /// Shipping method used for this payment like USPSParcel etc.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "shipping_method")]
        public string shipping_method { get; set; }

        /// <summary>
        /// Allows merchant's to share payer’s contact number with PayPal for the current payment. Final contact number of payer associated with the transaction might be same as shipping_phone_number or different based on Payer’s action on PayPal. The phone number must be represented in its canonical international format, as defined by the E.164 numbering plan
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "shipping_phone_number")]
        public string shipping_phone_number { get; set; }
    }
}
