//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using System.Collections.Generic;
using Newtonsoft.Json;

namespace PayPal.Api
{
    /// <summary>
    /// A batch payout header data object, which can be the response to a batch payout header request. Enables you to get payout header information for an entire batch payout request.
    /// <para>
    /// See <a href="https://developer.paypal.com/docs/api/">PayPal Developer documentation</a> for more information.
    /// </para>
    /// </summary>
    public class PayoutBatchHeader : PayPalRelationalObject
    {
        /// <summary>
        /// The PayPal-generated ID for a batch payout.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "payout_batch_id")]
        public string payout_batch_id { get; set; }

        /// <summary>
        /// The PayPal-generated batch status. If the batch payout passes preliminary checks, the status is `PENDING`.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "batch_status")]
        public string batch_status { get; set; }

        /// <summary>
        /// The date and time when processing for the batch payout began.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "time_created")]
        public string time_created { get; set; }

        /// <summary>
        /// The date and time when processing for the batch payout completed.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "time_completed")]
        public string time_completed { get; set; }

        /// <summary>
        /// The original batch payout header, as provided by the payment sender.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "sender_batch_header")]
        public PayoutSenderBatchHeader sender_batch_header { get; set; }

        /// <summary>
        /// The total amount, in U.S. dollars, requested for the payouts.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "amount")]
        public Currency amount { get; set; }

        /// <summary>
        /// The total estimate, in U.S. dollars, for the applicable payouts fees.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "fees")]
        public Currency fees { get; set; }

        /// <summary>
        /// An array of batch errors, if any.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "errors")]
        public List<Error> errors { get; set; }
    }
}
